// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import { fileURLToPath } from "node:url";

config({ path: fileURLToPath(new URL(".env", import.meta.url)) });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_SPODOP_URL"]!,
  },
});
